# Generated by Django 4.2.7 on 2023-11-07 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rota_tags_delete_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rota',
            old_name='titel',
            new_name='title',
        ),
    ]
