# Generated by Django 4.2.7 on 2023-11-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_titel_rota_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='tags',
            field=models.JSONField(null=True),
        ),
    ]
