# Generated by Django 4.2.7 on 2023-11-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_rota_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='tags',
            field=models.JSONField(max_length=50, null=True),
        ),
    ]
